### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by fanyui**
Synchronizing development branch with master branch this is one of it kind hence from now our master and dev will be identical so we can continue work on the dev am going to lock back the master after this pull request

### CODE REVIEW

**Comment by fanyui** [comment]
Sorry but someone have to review before i can merge though everything is ok but rules we created warrents it. So waiting for @Dirane  to approve or disapprove which ever one haha.

**Comment by fanyui** [comment]
And Ehh @Dirane  you can now pull from dev to have recent code .

**Review by Dirane — APPROVED** [review]
It works well as at now. Thumbs up!

**Review by Dirane — APPROVED** [review]
OK.

**Pull request merged**
