### PR TITLE
Modals

### PR DESCRIPTION
**Pull request by fanyui**
Completed the contact us page and some ui changes on this branch also added footer to both search page and search details page also there are some modifications on the database schema

### CODE REVIEW

**Review by Dirane — APPROVED** [review]
Let's just do it...

**Comment by fanyui** [comment]
you have approved but have not yet merged the pull request please try
merging now

**Comment by Dirane** [comment]
I approved and merged at once and I received the message which reads "No
conflicts with master branch".

**Comment by fanyui** [comment]
Yeah i was also sent the message that you have approved but just check if
you did merge it because you might have approved but didn't merge. they are
supposed to send me a message that you have merged the pull request. Also i
tried pulling from dev and nothing happened and i think i made the pull
request against dev not master so check and merge it into dev instead

**Pull request merged**
